#!/usr/bin/env python
"""
manage.py — Django's Command-Line Utility
=========================================
This file is AUTO-GENERATED by Django when you run 'django-admin startproject'.
You rarely edit this file directly.

Common commands you'll use:
  python manage.py runserver        → Start the development server
  python manage.py makemigrations   → Create migration files from model changes
  python manage.py migrate          → Apply migrations to the database
  python manage.py createsuperuser  → Create an admin user
  python manage.py shell            → Open a Python shell with Django loaded
  python manage.py startapp <name>  → Create a new app within the project
"""

import os
import sys


def main():
    """Run administrative tasks."""
    # Tell Django which settings file to use.
    # 'taskmanager.settings' means: look in the 'taskmanager' folder for 'settings.py'
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'taskmanager.settings')

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc

    # This passes command-line arguments (like 'runserver') to Django
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
