"""
tasks/apps.py — App Configuration
===================================
Every Django app has an AppConfig class that provides metadata about the app.
This file is AUTO-GENERATED by 'python manage.py startapp tasks'.

The AppConfig class:
  - Gives the app a human-readable name (for the admin panel)
  - Lets you run code when the app is ready (using ready() method)
  - Tells Django the default field type for auto-generated primary keys

You rarely edit this file directly, but you should know it exists.
The 'name' attribute must match the app folder name and the entry
in INSTALLED_APPS in settings.py.
"""

from django.apps import AppConfig


class TasksConfig(AppConfig):
    # The type of auto-created primary key fields.
    # BigAutoField uses a 64-bit integer (supports up to ~9 quintillion rows!).
    default_auto_field = 'django.db.models.BigAutoField'

    # name must match the app folder name.
    # This is what you put in INSTALLED_APPS in settings.py:
    #   INSTALLED_APPS = [..., 'tasks']  or  'tasks.apps.TasksConfig'
    name = 'tasks'

    # verbose_name: Human-readable name shown in the Django Admin
    verbose_name = 'Task Manager'
