"""
taskmanager/settings.py — Project Settings
============================================
This is the MAIN CONFIGURATION FILE for your entire Django project.
It was generated by 'django-admin startproject' and contains settings
for security, database, installed apps, templates, and more.

BEGINNERS: Focus on these key settings first:
  - SECRET_KEY: A unique random string used for security. Keep it secret!
  - DEBUG: Set to True during development, False in production.
  - INSTALLED_APPS: List of apps that are "turned on" in your project.
  - DATABASES: Database connection settings.
  - TEMPLATES: Where Django looks for HTML template files.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR points to the root folder of your project (where manage.py lives).
# Using pathlib.Path is the modern Python way to handle file paths.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# This key is used by Django to sign cookies, sessions, and other security data.
# In production, you would store this as an environment variable, NOT here.
SECRET_KEY = 'django-insecure-replace-this-with-a-real-secret-key-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True shows detailed error pages in the browser — helpful for development.
# DEBUG=False in production means Django shows a generic error page to users.
DEBUG = True

# Which hostnames are allowed to serve this app.
# Empty list = only localhost works (good for development).
# In production: ['yourwebsite.com', 'www.yourwebsite.com']
ALLOWED_HOSTS = []


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

# INSTALLED_APPS lists all the apps that are "active" in this Django project.
# Django itself has several built-in apps (django.contrib.*).
# We also add OUR app: 'tasks' (the app we created with startapp).
INSTALLED_APPS = [
    # Django's built-in apps:
    'django.contrib.admin',         # The /admin/ panel
    'django.contrib.auth',          # User authentication (login/logout)
    'django.contrib.contenttypes',  # Content type framework (needed by admin)
    'django.contrib.sessions',      # Session framework (remembers logged-in users)
    'django.contrib.messages',      # Flash messages (one-time notifications)
    'django.contrib.staticfiles',   # Serves CSS, JS, images in development

    # OUR custom app — this is the one we built!
    # 'tasks' matches the name of the folder and the AppConfig in tasks/apps.py
    'tasks',
]

# Middleware are functions that process requests/responses globally.
# They run before/after every view. Think of them as "plugins" for Django.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',    # Protects forms from CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT_URLCONF points to the urls.py file that Django checks FIRST.
# This is the "entry point" for all URL routing in your project.
ROOT_URLCONF = 'taskmanager.urls'

# TEMPLATES defines how Django finds and renders HTML templates.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS: Extra folders to look for templates (we use app-level templates).
        'DIRS': [],
        # APP_DIRS: True means Django will look for a 'templates/' folder
        # inside each app in INSTALLED_APPS. This is the recommended approach.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # This lets templates use {{ messages }} for flash messages
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION points to the WSGI callable for production deployments.
WSGI_APPLICATION = 'taskmanager.wsgi.application'


# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# We use SQLite — a simple file-based database.
# Perfect for learning! No server to set up, no installation required.
# The database is stored in a single file: db.sqlite3 (in your project root).
# In production, you'd typically switch to PostgreSQL or MySQL.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # The database type
        'NAME': BASE_DIR / 'db.sqlite3',          # The file path for the database
    }
}


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================
# These validators enforce password strength rules for user accounts.
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True   # Enable internationalization (translation support)
USE_TZ = True     # Store datetimes in UTC in the database (recommended)


# =============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# =============================================================================
# URL prefix for static files. With DEBUG=True, Django serves these automatically.
STATIC_URL = 'static/'


# =============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =============================================================================
# All models get an automatic 'id' primary key. This setting determines its type.
# BigAutoField uses a 64-bit integer — future-proofing your IDs.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
