"""
tasks/migrations/0001_initial.py — Initial Database Migration
=============================================================
WHAT ARE MIGRATIONS?

Migrations are Django's way of keeping your database schema in sync with
your Python models. Think of them as a version history for your database.

Every time you change a model (add a field, remove a field, change a type),
you run these two commands:

  1. python manage.py makemigrations
     → Creates a new migration FILE like this one
     → Django analyzes what changed in your models
     → It writes Python code describing the changes

  2. python manage.py migrate
     → APPLIES the migration files to the actual database
     → Creates/alters/drops tables and columns
     → Keeps track of which migrations have been applied

WHY NOT JUST EDIT THE DATABASE DIRECTLY?
  Migrations are tracked in version control (Git), so everyone on your team
  applies the same database changes in the same order. Without migrations,
  every developer's database would be out of sync.

THIS FILE:
  This is the INITIAL migration — it creates the 'tasks_task' table.
  It was auto-generated by running: python manage.py makemigrations

  You should NOT edit migration files manually (except in special cases).
  Let Django generate them.

  The 'dependencies' list shows which migrations must run BEFORE this one.
  '0001_initial' has no dependencies (it's the first migration for this app).
"""

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    # This is the FIRST migration for the 'tasks' app, so no dependencies.
    # Later migrations would list this one as a dependency:
    #   dependencies = [('tasks', '0001_initial')]
    initial = True
    dependencies = []

    operations = [
        # CreateModel creates the 'tasks_task' table in the database.
        # The name 'Task' maps to table name 'tasks_task' (app_model pattern).
        migrations.CreateModel(
            name='Task',
            fields=[
                # Auto-generated primary key (id field)
                # Every Django model gets this automatically unless you define
                # your own primary key field.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # title: VARCHAR(200) NOT NULL
                ('title', models.CharField(
                    help_text='Enter a short title for the task (max 200 characters)',
                    max_length=200
                )),

                # description: TEXT NULL (blank=True, null=True)
                ('description', models.TextField(
                    blank=True,
                    help_text='Optional: Add more details about the task',
                    null=True
                )),

                # is_complete: BOOLEAN NOT NULL DEFAULT FALSE
                ('is_complete', models.BooleanField(
                    default=False,
                    help_text='Check this box when the task is done'
                )),

                # created_at: DATETIME (auto-set on creation)
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Automatically set to the date/time the task was created'
                )),

                # updated_at: DATETIME (auto-set on every save)
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    help_text='Automatically updated every time the task is saved'
                )),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
